name: Go Services

jobs:
  build-backend:
    on:
      push:
        branches: [ "main", "master" ]
        paths: ['go-backend/**']
      pull_request:
        branches: [ "main", "master" ]
    name: Build Go Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./go-backend
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Download dependencies
      run: go mod download

    - name: Verify dependencies
      run: go mod verify

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

  build-lith-ranker:
    on:
      push:
        branches: [ "main", "master" ]
        paths: ['lith-ranker/**']
      pull_request:
        branches: [ "main", "master" ]
    name: Build Lith Ranker
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./lith-ranker
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Download dependencies
      run: go mod download

    - name: Verify dependencies
      run: go mod verify

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
