name: Node.js Services

jobs:
  build-dashboard:
    on:
      push:
        branches: [ "main", "master" ]
        paths: ['dashboard-frontend/**']
      pull_request:
        branches: [ "main", "master" ]
    name: Build Dashboard Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./dashboard-frontend
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22' # Next.js mới nhất yêu cầu Node >=20.9.0
        cache: 'npm'
        cache-dependency-path: dashboard-frontend/package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: Lint
      run: npm run lint
      continue-on-error: true

    - name: Build
      run: npm run build

  check-js-renderer:
    on:
      push:
        branches: [ "main", "master" ]
        paths: ['js-renderer/**']
      pull_request:
        branches: [ "main", "master" ]
    name: Check JS Renderer
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./js-renderer
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22' # Để chắc chắn thì dùng Node 22

    - name: Install dependencies
      run: npm install
    
    - name: Syntax Check
      run: node --check server.js
